# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneySent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=128)),
                ('to_address', models.CharField(max_length=128)),
                ('value', models.DecimalField(decimal_places=8, max_digits=16)),
                ('transaction_hash', models.CharField(max_length=128, null=True)),
                ('status', models.CharField(max_length=30)),
                ('creationDate', models.DateTimeField()),
                ('lastChangeDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=128)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
