# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_data', models.TextField()),
                ('last_update_blockchain', models.DateTimeField()),
                ('oer_data', models.TextField()),
                ('last_update_oer', models.DateTimeField()),
            ],
        ),
    ]
