from settings import *
import os

### ENVIRON_PROD
#  DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#  DJANGO_DEBUG=0
#  DJANGO_SECRET_KEY=$SECRET_KEY
#  ENABLE_PIWIK=1
#  DJANGO_SITE_PROTOCOL=https
#  DJANGO_SITE_HOST=freedomsponsors.org
#  DJANGO_EMAIL_HOST=localhost
#  DJANGO_EMAIL_PORT=25
#  DJANGO_EMAIL_USE_TLS=0
#  DJANGO_MEDIA_ROOT=/home/frespo/media
#  PAYPAL_USE_SANDBOX=0
#  FRESPO_LOG_FILE=/home/frespo/logs/frespo.log
#  BITCOIN_ENABLED=1
#  MOCK_OPENEXCHANGE_RATES=0
#  BITCOINRPC_CONN_REMOTE=1
#  BITCOINRPC_CONN_PORT=443
#  BITCOINRPC_CONN_USE_HTTPS=1
