# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 00:26
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitcoin_frespo', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('entity', models.CharField(max_length=30)),
                ('old_json', models.TextField(null=True)),
                ('new_json', models.TextField(null=True)),
                ('creationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, null=True)),
                ('creationDate', models.DateTimeField()),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('trackerURL', models.URLField(blank=True, null=True)),
                ('trackerURL_noprotocol', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_feedback', models.BooleanField()),
                ('is_sponsored', models.BooleanField()),
                ('status', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.models.upload_issue_image)),
                ('total_open_offers_usd', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('total_open_offers_btc', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('total_paid_offers_usd', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('total_paid_offers_btc', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('count_solutions_done', models.IntegerField(default=0)),
                ('count_solutions_in_progress', models.IntegerField(default=0)),
                ('createdByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField()),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='IssueCommentHistEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateTimeField()),
                ('content', models.TextField()),
                ('event', models.CharField(max_length=30)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IssueComment')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField()),
                ('lastChangeDate', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=16)),
                ('currency', models.CharField(max_length=10)),
                ('acceptanceCriteria', models.TextField(blank=True, null=True)),
                ('expirationDate', models.DateField(blank=True, null=True)),
                ('no_forking', models.BooleanField(default=True)),
                ('require_release', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=30)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Issue')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfferComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField()),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferCommentHistEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateTimeField()),
                ('content', models.TextField()),
                ('event', models.CharField(max_length=30)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OfferComment')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField()),
                ('lastChangeDate', models.DateTimeField()),
                ('paykey', models.CharField(blank=True, max_length=128, null=True)),
                ('confirm_key', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(max_length=30)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=16)),
                ('total', models.DecimalField(decimal_places=8, max_digits=16)),
                ('currency', models.CharField(max_length=10)),
                ('bitcoin_transaction_hash', models.CharField(max_length=128, null=True)),
                ('total_bitcoin_received', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('bitcoin_fee', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('offer_currency', models.CharField(max_length=10, null=True)),
                ('offer2payment_suggested_rate', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('usd2payment_rate', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('bitcoin_receive_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bitcoin_frespo.ReceiveAddress')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('event', models.CharField(max_length=30)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypalEmail', models.EmailField(max_length=256, null=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=16)),
                ('money_sent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bitcoin_frespo.MoneySent')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Payment')),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('creationDate', models.DateTimeField()),
                ('homeURL', models.URLField(blank=True, null=True)),
                ('trackerURL', models.URLField(blank=True, null=True)),
                ('image3x1', models.ImageField(blank=True, null=True, upload_to=core.models.upload_project_image)),
                ('createdByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('redirectto_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField()),
                ('lastChangeDate', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('accepting_payments', models.BooleanField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Issue')),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('objtype', models.CharField(max_length=200)),
                ('objid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypalEmail', models.EmailField(max_length=256)),
                ('screenName', models.CharField(max_length=64)),
                ('realName', models.CharField(max_length=256)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('receiveAllEmail', models.BooleanField()),
                ('brazilianPaypal', models.BooleanField()),
                ('is_primary_email_verified', models.BooleanField()),
                ('is_paypal_email_verified', models.BooleanField()),
                ('hide_from_userlist', models.BooleanField()),
                ('preferred_language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('bitcoin_receive_address', models.CharField(blank=True, max_length=128)),
                ('paypal_verified', models.BooleanField()),
                ('receiveEmail_issue_comments', models.BooleanField()),
                ('receiveEmail_issue_work', models.BooleanField()),
                ('receiveEmail_issue_offer', models.BooleanField()),
                ('receiveEmail_issue_payment', models.BooleanField()),
                ('receiveEmail_announcements', models.BooleanField()),
                ('can_change_username', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField()),
                ('date_last_updated', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objid', models.IntegerField()),
                ('reason', models.CharField(max_length=30)),
                ('entity', models.CharField(max_length=60)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paymentpart',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Solution'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Issue'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='issue_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.IssueComment'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Offer'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Payment'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Solution'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
